# Generated by Django 6.0.3 on 2026-04-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftrequiredcertification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftrequiredcertification',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='shiftrequiredcertification',
            name='shift',
        ),
        migrations.AlterUniqueTogether(
            name='staffrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='staffspecialty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffspecialty',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='staffspecialty',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='patientload',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certification',
            name='dependencies',
            field=models.ManyToManyField(related_name='required_for', to='api.certification'),
        ),
        migrations.AddField(
            model_name='shift',
            name='required_certifications',
            field=models.ManyToManyField(related_name='required_shifts', to='api.certification'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(related_name='staff_members', to='api.role'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialties',
            field=models.ManyToManyField(related_name='staff_members', to='api.specialty'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.absencetype'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='impacts_quota',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careunit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.service'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contracttype'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='workload_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientload',
            name='care_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_loads', to='api.careunit'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.service'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='care_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.careunit'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='min_staff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.shifttype'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.shift'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_specialties', to='api.specialty'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffcertification',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='staffloan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffloan',
            name='from_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_from', to='api.service'),
        ),
        migrations.AlterField(
            model_name='staffloan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='staffloan',
            name='to_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_to', to='api.service'),
        ),
        migrations.AlterField(
            model_name='staffserviceassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='api.staff'),
        ),
        migrations.AlterModelTable(
            name='absence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='absencetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='careunit',
            table=None,
        ),
        migrations.AlterModelTable(
            name='certification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contract',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contracttype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patientload',
            table=None,
        ),
        migrations.AlterModelTable(
            name='preference',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicestatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shift',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shiftassignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shifttype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='specialty',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staffcertification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staffloan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staffserviceassignment',
            table=None,
        ),
        migrations.DeleteModel(
            name='CertificationDependency',
        ),
        migrations.DeleteModel(
            name='ShiftRequiredCertification',
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
        migrations.DeleteModel(
            name='StaffSpecialty',
        ),
    ]
